// Builds src/data/tajweed/{001..114}.json + src/data/tajweed/index.ts: the tajweed-coloured text of every
// surah (quran.com uthmani_tajweed, the same source and URL as src/core/quran/tajweedApi.ts), bundled so
// the mushaf shows tajweed colours offline from the first launch.
// Each file is the raw markup, one string per ayah in order; the app parses it with the same
// parseTajweedMarkup the network path uses, so there is a single parser.
// Usage: npm run build:tajweed
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "src/data/tajweed");
const TAJWEED_URL = "https://api.quran.com/api/v4/quran/verses/uthmani_tajweed";
const surahNames = JSON.parse(fs.readFileSync(path.join(root, "src/data/surah-names.json"), "utf8"));
const pad = (n) => String(n).padStart(3, "0");

async function fetchSurah(surah, attempt = 1) {
  try {
    const response = await fetch(`${TAJWEED_URL}?chapter_number=${surah}`);
    if (!response.ok) throw new Error(`quran.com answered ${response.status} for surah ${surah}`);
    const { verses } = await response.json();
    const byAyah = new Map(verses.map((verse) => [Number.parseInt(verse.verse_key.split(":")[1] ?? "0", 10), verse.text_uthmani_tajweed]));
    const ayahCount = surahNames[surah - 1][3];
    const markup = Array.from({ length: ayahCount }, (_, index) => byAyah.get(index + 1));
    if (byAyah.size !== ayahCount || markup.some((text) => !text)) {
      throw new Error(`Surah ${surah}: expected ${ayahCount} ayahs, got ${byAyah.size}`);
    }
    return markup;
  } catch (error) {
    if (attempt >= 4) throw error;
    await new Promise((resolve) => setTimeout(resolve, 1000 * attempt));
    return fetchSurah(surah, attempt + 1);
  }
}

fs.mkdirSync(outDir, { recursive: true });
const surahs = Array.from({ length: 114 }, (_, index) => index + 1);
let next = 0;
let totalBytes = 0;
await Promise.all(
  Array.from({ length: 6 }, async () => {
    while (next < surahs.length) {
      const surah = surahs[next++];
      const markup = await fetchSurah(surah);
      const file = path.join(outDir, `${pad(surah)}.json`);
      fs.writeFileSync(file, JSON.stringify(markup));
      totalBytes += fs.statSync(file).size;
    }
  }),
);

const cases = surahs.map((surah) => `    case ${surah}:\n      return require("./${pad(surah)}.json");`).join("\n");
const index = `// Generated by scripts/build-tajweed.mjs — do not edit by hand (npm run build:tajweed).
import { parseTajweedMarkup, type TajweedAyah } from "@/core/quran/tajweedApi";

/** The raw uthmani_tajweed markup of a surah, one string per ayah. A switch of literal requires so
 * Metro bundles every surah but only evaluates the one asked for. */
function raw(surah: number): string[] | null {
  switch (surah) {
${cases}
    default:
      return null;
  }
}

/** A surah's tajweed segments from the bundled data, or null for a number outside 1..114. */
export function loadBundledTajweed(surah: number): TajweedAyah[] | null {
  const markup = raw(surah);
  return markup ? markup.map((text, index) => ({ numberInSurah: index + 1, segments: parseTajweedMarkup(text) })) : null;
}
`;
fs.writeFileSync(path.join(outDir, "index.ts"), index);
console.log(`Wrote ${path.relative(root, outDir)}: 114 surahs, ${(totalBytes / 1024).toFixed(0)} KB`);
