// Builds src/data/tafsir/{001..114}.json + src/data/tafsir/index.ts: Tafsir al-Muyassar for all 6236
// ayahs (the website's tafsir, api.alquran.cloud edition ar.muyassar), bundled so the tafsir works
// offline from the first launch. One file per surah, like src/data/tajweed: opening a tafsir loads that
// surah's text only, instead of keeping all 2.4 MB in memory.
// Usage: npm run build:tafsir
//        node scripts/build-tafsir.mjs --from <old tafsir-muyassar.json>   (re-split without the network)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "src/data/tafsir");
const BOM = new RegExp(`^${String.fromCodePoint(0xfeff)}`);
const surahNames = JSON.parse(fs.readFileSync(path.join(root, "src/data/surah-names.json"), "utf8"));
const pad = (n) => String(n).padStart(3, "0");

async function fetchTexts() {
  const response = await fetch("https://api.alquran.cloud/v1/quran/ar.muyassar");
  if (!response.ok) throw new Error(`alquran.cloud answered ${response.status}`);
  const { data } = await response.json();
  return data.surahs.flatMap((surah) => surah.ayahs.map((ayah) => ayah.text.replace(BOM, "").trim()));
}

const fromIndex = process.argv.indexOf("--from");
// One string per ayah, in mushaf order: index = global ayah number - 1 (the same order as mushaf-hafs.json).
const texts = fromIndex > 0 ? JSON.parse(fs.readFileSync(process.argv[fromIndex + 1], "utf8")).texts : await fetchTexts();
if (texts.length !== 6236) throw new Error(`Expected 6236 ayahs, got ${texts.length}`);
if (texts.some((text) => !text)) throw new Error("Some ayahs have no tafsir text");

fs.mkdirSync(outDir, { recursive: true });
let offset = 0;
let totalBytes = 0;
for (const [number, , , ayahCount] of surahNames) {
  const file = path.join(outDir, `${pad(number)}.json`);
  fs.writeFileSync(file, JSON.stringify(texts.slice(offset, offset + ayahCount)));
  totalBytes += fs.statSync(file).size;
  offset += ayahCount;
}
if (offset !== texts.length) throw new Error(`surah-names.json covers ${offset} ayahs, the tafsir ${texts.length}`);

const cases = surahNames.map(([number]) => `    case ${number}:\n      return require("./${pad(number)}.json");`).join("\n");
fs.writeFileSync(
  path.join(outDir, "index.ts"),
  `// Generated by scripts/build-tafsir.mjs — do not edit by hand (npm run build:tafsir).
// Source: api.alquran.cloud ar.muyassar.

/** A surah's tafsir, one string per ayah. A switch of literal requires so Metro bundles every surah but
 * only evaluates the one asked for. */
export function loadBundledTafsir(surah: number): string[] | null {
  switch (surah) {
${cases}
    default:
      return null;
  }
}
`,
);
console.log(`Wrote ${path.relative(root, outDir)}: 114 surahs, ${(totalBytes / 1024).toFixed(0)} KB`);
