package com.almanara.background

import android.app.AlarmManager
import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.content.*

/**
 * Redraws the "next prayer" home-screen widget (react-native-android-widget's NextPrayer provider)
 * when a prayer begins, so it doesn't keep showing a prayer that has already started. Every call is
 * best-effort: a widget failure must never affect the adhan or the schedule.
 */
internal object PrayerWidget {
  // Generated by the react-native-android-widget config plugin as <namespace>.widget.<name>.
  private const val PROVIDER = "com.almanara.app.widget.NextPrayer"

  fun refresh(context: Context) = runCatching {
    val provider = ComponentName(context.packageName, PROVIDER)
    val ids = AppWidgetManager.getInstance(context).getAppWidgetIds(provider)
    if (ids.isEmpty()) return@runCatching
    context.sendBroadcast(
      Intent(AppWidgetManager.ACTION_APPWIDGET_UPDATE).setComponent(provider)
        .putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, ids),
    )
  }

  /**
   * One inexact wake-up at [at] (the next prayer the widget shows), so the widget also moves on when
   * the adhan is off. Replaces the previous one. No exact-alarm permission is needed for this.
   */
  fun schedule(context: Context, at: Long) = runCatching {
    val intent = PendingIntent.getBroadcast(
      context, 7106, Intent(context, WidgetRefreshReceiver::class.java),
      PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
    )
    val alarms = BackgroundState.alarms(context)
    if (at <= System.currentTimeMillis()) alarms.cancel(intent)
    else alarms.setAndAllowWhileIdle(AlarmManager.RTC, at, intent)
  }
}

class WidgetRefreshReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    PrayerWidget.refresh(context)
  }
}
